services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: atm-backend
    ports:
      - "7575:7575"
    networks:
      - atmnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: atm-frontend
    ports:
      - "8080:80"
    networks:
      - atmnet

networks:
  atmnet:
