# Sunucu Ayarları
server.port=8080
server.servlet.context-path=/atm/api

# Uygulama Adı
spring.application.name=atm-withdraw-api

# Logging (Günlükleme) Ayarları (İsteğe bağlı)
logging.level.root=INFO
logging.level.com.example.atm=DEBUG