server.port=7575
server.servlet.context-path=/api
spring.application.name=atm-withdraw-api

spring.datasource.url=jdbc:postgresql://db:5433/atm_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true


spring.jpa.properties.hibernate.default_schema=public
spring.jpa.open-in-view=false